# This is a basic workflow to help you get started with Actions

name: Build and test 

on:
  push:
    branches: [ master ]

  workflow_dispatch:


jobs:

  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Swift build 
        run: swift build -v 
  test:
    runs-on: macos-latest
    needs: build
    steps:
      - name: swift test
        run: swift test -v
    

